/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "/sec.": "/秒。",
    "Activate": "启用",
    "Alerts you of incoming meteorites, allowing you to avoid them.": "提醒您即将到来的陨石，让您避开它们。",
    "Amount": "数量",
    "Asset": "资产",
    "Automation": "自动化",
    "Bonus not claimed. Enable remote storage in the settings and log in every day to receive a bonus!": "奖金未领取。 在设置中启用远程存储，每天登录即可领取奖励！",
    "Build a factory to produce quantum computers.": "建造一家工厂来生产量子计算机。",
    "Buy Robot (€$ 500)": "购买机器人（€$ 500）",
    "Buy Solar Panel (€$ 2,000)": "购买太阳能电池板（€$ 2,000）",
    "Complete the project 'Quantum Computer Factory' to build quantum computers.": "完成“量子计算机工厂”项目来建造量子计算机。",
    "Deposit": "订金",
    "Doubles the amount of Unobtanium mined.": "开采的 Unobtanium 数量加倍。",
    "Efficiency:": "效率：",
    "Epoch:": "时代：",
    "Free": "免费",
    "Geiger Counter": "盖革计数器",
    "Generate OPS": "生成OPS",
    "Generates more OPS for completing projects.": "生成更多 OPS 来完成项目。",
    "Hedge Fund": "对冲基金",
    "Imprint": "印记",
    "Increase Storage Capacity\n(€$ 500)": "增加存储容量\n(€$ 500)",
    "Increases the chances of finding rare Unobtanium deposits by 20%.": "发现稀有 Unobtanium 矿床的几率提高 20%。",
    "Increases the energy efficiency of your operation by 50%.": "将您的运营能源效率提高 50%。",
    "Increases the speed of robots by 50%.": "使机器人的速度提高 50%。",
    "Low Risk": "低风险",
    "Meteorite Detector": "陨石探测器",
    "Mine Unobtanium": "矿山 Unobtanium",
    "Minigame": "小游戏",
    "Mining Rate:": "采矿率：",
    "No data": "没有数据",
    "Not enough OPS": "没有足够的 OPS",
    "OK": "好的",
    "Play": "开始",
    "Power Consumption:": "能量消耗：",
    "Power Grid Upgrade": "电网升级",
    "Price": "价格",
    "Privacy": "隐私",
    "Profit": "利润",
    "Projects": "项目",
    "Quantum Computer Factory": "量子计算机工厂",
    "Quantum Computers": "量子计算机",
    "Quantum Computers:": "量子计算机：",
    "Robotic Arms": "机械臂",
    "Robots": "机器人",
    "Robots:": "机器人：",
    "Rock Smasher": "碎石者",
    "Sales Tax:": "销售税：",
    "Select risk level": "选择风险级别",
    "Sell": "出售",
    "Solar flare passed. Mining output returned to normal.": "太阳耀斑过去了。 矿业产出恢复正常。",
    "Solar Panels": "太阳能板",
    "Solar Panels:": "太阳能板：",
    "Space Miner": "太空矿工",
    "The world needs more Unobtanium!": "世界需要更多 Unobtanium！",
    "Total": "总计",
    "Total Sold:": "总销量：",
    "Trading": "贸易",
    "Trading Engine Win Rate:": "交易引擎胜率：",
    "Unobtanium in storage:": "储存中的Unobtanium：",
    "Unobtanium Price:": "Unobtanium价格：",
    "Unobtanium Refinery": "Unobtanium精炼厂",
    "Upgrade Solar Panels (€$ 8,000)": "升级太阳能电池板（€$ 8,000）",
    "Upgrade Trading Engine\n(€$ 50,000)": "升级交易引擎\n（€$ 50,000）",
    "View Achievements": "查看成就",
    "Withdraw": "提取",
    "You need to complete the project \"Hedge Fund Investment\" before you can deposit.": "您需要先完成项目“对冲基金投资”才可以存款。",
    "Buy now": "立即购买",
    "Buy Robot": "购买机器人",
    "Buy with": "购买花费",
    "Cancel": "取消",
    "completed in:": "完成时间：",
    "Drone Swarm": "无人机群",
    "Earn money by smashing as many rocks as possible. Caution: You lose a life if you smash a rock that releases poisonous gas.": "通过粉碎尽可能多的石头来赚钱。 注意：如果你砸碎释放有毒气体的岩石，你就会丧命。",
    "Enable sound": "启用声音",
    "Market Research": "市场调查",
    "OPS generated!": "OPS 已生成！",
    "OPS/sec.": "OPS/秒。",
    "Pay €$ 500 to buy a robot and automatically mine 1 Unobtanium per second?": "支付 500 欧元购买机器人并每秒自动开采 1 Unobtanium？",
    "RESET GAME": "重置游戏",
    "Reset the game:": "重置游戏：",
    "Robot malfunction resolved. Mining output returned to normal.": "机器人故障已解决。 矿业产出恢复正常。",
    "Sell Unobtanium for 5% more for 10 epochs.": "以 5% 以上的价格出售 Unobtanium，持续 10 个周期。",
    "Stardust": "星尘",
    "Stardust Balance:": "星尘平衡：",
    "Unlocks a fleet of drones that mine Unobtanium automatically.": "解锁一支自动开采 Unobtanium 的无人机舰队。",
    "A rare solar eclipse has occurred, reducing the efficiency of solar panels and decreasing production by 15% for 2 epochs.": "发生了罕见的日食，导致太阳能电池板的效率降低，产量减少 15%，持续 2 个周期。",
    "and earn": "并赚取",
    "Collect reward": "领取奖励",
    "Game Over": "游戏结束",
    "High Risk": "高风险",
    "Medium Risk": "中风险",
    "Play again": "再玩一次",
    "rocks": "岩石",
    "Solar Eclipse resolved. Mining output returned to normal.": "日食已解决。 矿业产出恢复正常。",
    "Solar Eclipse! Mining output decreased by 15% for 2 epochs.": "日食！ 挖矿产出连续 2 个周期下降 15%。",
    "Space Elevator": "太空电梯",
    "Transports Unobtanium from the mining site to Earth instantly, reducing transportation costs and increasing your profit by 50%.": "将 Unobtanium 从矿场即时运输到地球，降低运输成本并使您的利润增加 50%。",
    "Wallstreetbets": "华尔街投注",
    "Welcome back!": "欢迎回来！",
    "You smashed": "你砸坏了",
    "A dust storm is approaching! Mining output decreased by 10% for 2 epochs.": "沙尘暴即将来临！ 挖矿产出连续 2 个周期下降 10%。",
    "A massive dust storm has hit the mining site, reducing visibility and decreasing production by 10% for 2 epochs.": "一场大规模沙尘暴袭击了矿区，导致能见度降低，产量连续 2 个周期减少 10%。",
    "Acquires a rival mining company, increasing production capacity by 50%": "收购竞争对手矿业公司，产能提高 50%",
    "Advertising Campaign": "广告攻势",
    "Alien Technology": "外星科技",
    "Black Hole Projector": "黑洞投影仪",
    "Create your own hedge fund to invest in the markets of the universe.": "创建您自己的对冲基金来投资宇宙市场。",
    "Creates a black hole that pulls in all nearby asteroids and collects their resources.": "创建一个黑洞，吸引所有附近的小行星并收集它们的资源。",
    "Gain a monopoly on Unobtanium sales, increasing the sale price by 50%": "获得 Unobtanium 销售垄断权，将销售价格提高 50%",
    "Hedge Fund Investment": "对冲基金投资",
    "Hire a sales manager that sells the mined Unobtanium as soon as it reaches the warehouse.": "聘请一名销售经理，在开采的 Unobtanium 到达仓库后立即将其出售。",
    "Increases demand for Unobtanium and raises the price by 25% for 3 epochs.": "增加对 Unobtanium 的需求并将价格提高 25%，持续 3 个时期。",
    "Market Analysis Robot": "市场分析机器人",
    "Marketing Campaign": "营销活动",
    "Merger and Acquisition": "并购",
    "Mining Cartel": "矿业卡特尔",
    "Provides detailed market analysis and suggests optimal sell times.": "提供详细的市场分析并建议最佳销售时间。",
    "Sales Manager": "销售经理",
    "Sell Unobtanium for 10% more for 10 epochs.": "以 10% 以上的价格出售 Unobtanium，持续 10 个周期。",
    "Sell Unobtanium for 50% more for 20 epochs.": "以 50% 以上的价格出售 Unobtanium，持续 20 个周期。",
    "Space Market Dominance": "太空市场主导地位",
    "Supply shortage resolved. Mining output returned to normal.": "供应短缺得到解决。 矿业产出恢复正常。",
    "Supply shortage! Mining output decreased by 15% for 3 epochs.": "货源紧缺！ 挖矿产出连续 3 个周期下降 15%。",
    "The dust storm has cleared. Mining output returned to normal.": "沙尘暴已经散去。 矿业产出恢复正常。",
    "Unlocks the ability to mine Unobtanium from alien asteroids, increasing the amount mined by 50%.": "解锁从外星小行星开采 Unobtanium 的能力，使开采量增加 50%。",
    "Your supply of mining equipment has run low, decreasing production by 15% for 3 epochs.": "您的采矿设备供应不足，产量在 3 个时期内减少了 15%。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'OPS': 'OPS',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "% capacity)": "% 容量)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+) OPS$/,
    /^x([\d\.,]+)$/,
    /^€\$ ([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You were offline for (.+).\nUnobtanium mined: (.+)\nEuroDollar earned: €\$ (.+)\nOPS generated: (.+)$/, '您离线了 $1。\n开采 Unobtanium: $2\n赚取 欧元: €$ $3\n生成 OPS: $4'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);